### ISSUE TITLE
ZeroDivisionError with run_training.py

### ISSUE THREAD

**Issue by mbarnig** [as-ideas/DeepPhonemizer#2]
To get familiar with the DeepPhoneme tool, I run the two example python files in the repository. `run_prediction.py` works as expected, but `run_training-py` generates an error. 

Here is the log output:
```     
mbarnig@mbarnig-MS-7B22:~/DeepPhonemizer$ python3 ./run_training.py
2021-05-25 22:40:49,343.343 INFO preprocess:  Preprocessing, train data: with 300 files.
2021-05-25 22:40:49,344.344 INFO preprocess:  Performing random split with num val: 100
2021-05-25 22:40:49,344.344 INFO preprocess:  Processing train data...
0it [00:00, ?it/s]
2021-05-25 22:40:49,347.347 INFO preprocess:  
Saving datasets to: /home/mbarnig/DeepPhonemizer/datasets
2021-05-25 22:40:49,348.348 INFO preprocess:  Preprocessing. 
Train counts (deduplicated): []
Val counts (including duplicates): [('de', 200), ('en_us', 100)]
2021-05-25 22:40:49,352.352 INFO train:  Initializing new model from config...
2021-05-25 22:40:49,380.380 INFO train:  Checkpoints will be stored at /home/mbarnig/DeepPhonemizer/checkpoints
2021-05-25 22:40:49.464084: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "./run_training.py", line 14, in <module>
    train(config_file=config_file)
  File "/home/mbarnig/DeepPhonemizer/dp/train.py", line 46, in train
    trainer.train(model=model,
  File "/home/mbarnig/DeepPhonemizer/dp/training/trainer.py", line 74, in train
    start_epoch = checkpoint['step'] // len(train_loader)
ZeroDivisionError: integer division or modulo by zero

```    
Please advise me what is missing. Thank you.

Marco Barnig

**Comment by cschaefer26** [comment]
Hi thanks for letting me know. The problem here is that I added deduplication to the preprocessing which removed all training data for this dummy example. I updated the example.

**Comment by mbarnig** [comment]
@cschaefer26. Thank you for the reply. The dummy training example is now working. Here is the Tensorboard screenshot :   

![deepphonemizer-tensorboard](https://user-images.githubusercontent.com/1360633/119704214-abe0ca00-be57-11eb-87e2-16cd66722579.png)

I close the issue and continue my trials with a real data-file for the luxembourgish language.

**Comment by cschaefer26** [comment]
Glad to hear, keep me updated on how it goes!

**Comment by cschaefer26** [comment]
@mbarnig  If you run into any issues with the training let me know, any input will be valuable to me as the repo is new and work in progress. I am happy to help.
